#!/bin/bash
#
# BanInformer Single Server Report
#
# Server 1
# IP 104.131.129.178
#
# Designed: Wed May  6 07:05:43 PDT 2015
# Scott "Roguehorse" DuBois
#

# Order to run separate programs
# 1. All
# 2. Daily
# 3. Jail
# 4. Unban
# 5. Aggressive
# 6. Block
# 7. Country

# Daily Data
# Start ---------------
#
# End -----------------

# All Data
# Start ---------------
#
# End -----------------

# Perma Data
# Start ---------------
#
# End -----------------

# Aggression Data
# Start ---------------
#
# End -----------------

# Country Data
# Start ---------------
#
# End -----------------

data=./files/report/test_data.txt
ip="104.131.129.178"
rfq=240
ymd=$(date +%Y-%m-%d)
hm=$(date +%H:%M)
#declare -a repData=('432' '87' '345' '95000000' '12' '6' '30.187.254.30' '30.187' 'China')
declare -a repData
i=0

if [ -f $data ]; then

  while read -r line; do
    
    repData[$i]=$(echo $line)
    ((i++))

  done < $data

fi
    
repData[6]=$((repData[0] - repData[1]))

# create report
rpt=./files/report/bi_ssr.txt
if [ -f $rpt ]; then
  rm ./files/report/bi_ssr.txt
fi
echo "" > ./files/report/bi_ssr.txt
printf "\n\nBanInformer\n" >> ./files/report/bi_ssr.txt
printf "Single Server Report\n" >> ./files/report/bi_ssr.txt
printf "Report Date: $ymd\n" >> ./files/report/bi_ssr.txt
printf "Report Time: $hm\n\n" >> ./files/report/bi_ssr.txt
# number of = is 60
printf "============================================================\n\n" >> ./files/report/bi_ssr.txt
printf "Server Reporting IP            $ip\n"                >> ./files/report/bi_ssr.txt
printf "Reporting Frequency (min)      $rfq\n\n"             >> ./files/report/bi_ssr.txt
printf "Banned IP Total                ${repData[0]}\n"      >> ./files/report/bi_ssr.txt
printf "Banned IP Today                ${repData[1]}\n"      >> ./files/report/bi_ssr.txt
printf "Attempts Delta                 ${repData[6]}\n\n"    >> ./files/report/bi_ssr.txt
printf "IP Ban Time (sec)              ${repData[2]}\n"      >> ./files/report/bi_ssr.txt
printf "IP's Released Today            ${repData[3]}\n\n"    >> ./files/report/bi_ssr.txt
printf "Most Aggressive Block          ${repData[4]}\n"      >> ./files/report/bi_ssr.txt
printf "Country Origin of Block        ${repData[5]}\n\n\n"  >> ./files/report/bi_ssr.txt

cp ./files/report/bi_ssr.txt ./results

cp ./files/report/bi_ssr.txt ./results/$ymd-report.txt

# End of Script 
