#!/bin/bash

touch ./files/whotest.txt
whoFile=./files/whoisCtry.txt
declare -a whoarr
i=0

while read -r line; do

  who=$(echo $line | grep country | cut --delimiter=' ' --fields=2)

  if [[ X"$who" != X"" ]]; then 

    whoarr[$i]=$(echo $who)

    ((i++))

  else

    :

  fi

done < $whoFile 

echo "${whoarr[0]}" >> ./files/whotest.txt



